name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed
    branches: [ main ]
  
  # Allow manual deployment
  workflow_dispatch:

jobs:
  deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package.json'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build for production
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://devops-deployment-pixel-pulse.onrender.com' }}
          VITE_APP_TITLE: "PixelPulse"
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          vercel-args: '--prod'
      
      - name: Health check
        run: |
          echo "Waiting for deployment to be available..."
          sleep 30
          curl -f ${{ secrets.FRONTEND_URL || 'https://pixel-pulse-five.vercel.app' }} || echo "Health check failed, but deployment may still be in progress"
      
      - name: Deployment summary
        run: |
          echo "🚀 Frontend deployment completed!"
          echo "📱 Application URL: ${{ secrets.FRONTEND_URL || 'https://pixel-pulse-five.vercel.app' }}"
          echo "📊 Build info: ${{ github.sha }}"
